### PR TITLE
Active Support cache, Dalli Store adapters, and removing Redis requirement

### PR DESCRIPTION
**Pull request by daveallie**
Set the default adapter to use ActiveSupport::Cache::Memory store.

Removed Redis as a requirement for the gem, and throws an error if the user tries to use the Redis adapter without the Redis gem.

Also added a Dalli store adapter. 

---

Edit: Now moving toward using [Moneta](https://github.com/minad/moneta) to delegate caching logic.
#### TODO:
- [x] Include Moneta and remove old adapters
- [ ] Test several adapters to make sure expiry and incrementing is working as intended
- [ ] Update readme & changelog

### CODE REVIEW

**Comment by gottfrois** [comment]
sounds cool, i'll review that indeph later :) Thanks for the PR

**Comment by gottfrois** [comment]
Thanks for the pull request. What do you think if we used https://github.com/minad/moneta instead?

**Comment by daveallie** [comment]
I like the idea of delegating the logic of cache selection and implementation to another gem, the way it was originally implemented was pretty specific with the requirement of Redis, and the changes I made are going to be annoying to replicate for each new adapter that people want.

You're welcome to take this on, I'll come to it when I get some time in the near future otherwise.

**Comment by eni9889** [comment]
It would be great if this PR was merged. It is the only reason I have not implemented this gem in my app. Great work BTW to both of you.

**Comment by gottfrois** [comment]
I'll have a look at moneta but i'm quite confused with their dependencies requirements... Do they really require to install all their supported backends define in the gemspec !?

That would not solve the issue of having unecessary gems installed such as redis :(

**Comment by daveallie** [comment]
Dependencies in the [Gemfile](https://github.com/minad/moneta/blob/master/Gemfile) are for development only, it doesn't look like it requires anything on install but as you initialise Moneta with a specific adapter, it will require it. I have Redis installed on my system, but not Cassandra, and this is what happens:

``` ruby
2.3.0 :004 > Moneta.new(:Redis)
 => #<Moneta::Transformer::MarshalPrefixKeyMarshalValue:0x007fe8dc9c95d8 @adapter=#<Moneta::Adapters::Redis:0x007fe8dc9ca168 @default_expires=nil, @backend=#<Redis client v3.2.2 for redis://127.0.0.1:6379/0>>, @prefix="">
2.3.0 :005 > Moneta.new(:Cassandra)
LoadError: cannot load such file -- cassandra
    from /Users/david/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/david/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/david/.rvm/gems/ruby-2.3.0/gems/moneta-0.8.0/lib/moneta/adapters/cassandra.rb:1:in `<top (required)>'
    from /Users/david/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/david/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/david/.rvm/gems/ruby-2.3.0/gems/moneta-0.8.0/lib/moneta.rb:125:in `const_get'
    from /Users/david/.rvm/gems/ruby-2.3.0/gems/moneta-0.8.0/lib/moneta.rb:125:in `new'
    from (irb):5
    from /Users/david/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
```

**Comment by gottfrois** [comment]
ah cool! Thanks for looking at this @daveallie

**Comment by daveallie** [comment]
@gottfrois I just realised that each time the key gets updated, the expiry is reset (see [here](https://github.com/gottfrois/grape-attack/blob/master/lib/grape/attack/counter.rb#L23)).

And although this 3d3fad6c11c9c2fab06788dafaba64fbfc91e747 commit message wasn't correct in explaining it, it is pretty broken. Here's an example:
1. Setup endpoint that allows 100 requests per 1 minute
2. Make 90 requests in 1 second
3. 50 seconds later make 9 more requests
4. 20 seconds after that (throttling should be reset at this point) make 2 requests

That very last request will be rate limited, as the 1 minute window is reset after each request. The request should have been let through as the window should have been reset 60 seconds after the first request. 

3d3fad6c11c9c2fab06788dafaba64fbfc91e747 makes a poor attempt to fix it, and 7a2a0e9e40f7edfe966ad575f1186cfb4eddef63 makes it work across all adapters

**Comment by gottfrois** [comment]
Oh really? Good catch. Can we make seperate PRs for this maybe?

**Comment by gottfrois** [comment]
BTW don't forget to rebase against master

**Comment by daveallie** [comment]
This is over 7 years stale, I've completely lost context on the codebase and don't really have the time or motivation to get it resolved. Am going to close it, but welcome anyone else to pick this back up if it's still an issue

**Pull request closed without merging**
